services:
  odoo:
    build: .
    ports:
      - "8069:8069"
    environment:
      - DB_HOST=aws-0-eu-west-3.pooler.supabase.com
      - DB_PORT=5432
      - DB_USER=postgres.yjctpbwmktnmhlanftxh
      - DB_PASSWORD=#$MM*vfCwN75T-Z
      - DB_NAME=postgres
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons

volumes:
  odoo-web-data:
