services:
  odoo:
    build:
      context: .
      args:
        OPENAI_API_KEY: ${OPENAI_API_KEY}
        HOST_UID: ${UID}
        HOST_GID: ${GID}
        DB_HOST: ${DB_HOST}
        DB_PORT: ${DB_PORT}
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_NAME: ${DB_NAME}
        PGPASSWORD: ${PGPASSWORD}
        ODOO_DB: ${ODOO_DB}
        ODOO_USERNAME: ${ODOO_USERNAME}
        ODOO_PASSWORD: ${ODOO_PASSWORD}
        PG_URI: ${PG_URI}
    ports:
      - "8069:8069"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PGPASSWORD=${PGPASSWORD}
      - ODOO_DB=${ODOO_DB}
      - ODOO_USERNAME=${ODOO_USERNAME}
      - ODOO_PASSWORD=${ODOO_PASSWORD}
      - PG_URI=${PG_URI}
      - PYTHONUNBUFFERED=1
      - TERM=xterm-color
      - ODOO_LOGFILE=/var/log/odoo/odoo.log
      - ODOO_WORKERS=${ODOO_WORKERS:-0}
      - ODOO_LOG_LEVEL=${ODOO_LOG_LEVEL:-info}
      - ODOO_MAX_CRON_THREADS=${ODOO_MAX_CRON_THREADS:-2}
      - ODOO_PROXY_MODE=${ODOO_PROXY_MODE:-False}
      - DB_MAXCONN=${DB_MAXCONN:-64}
      - DB_TEMPLATE=${DB_TEMPLATE:-template0}
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons/setup_odoo:/mnt/setup_odoo
      - ./addons/social_media:/mnt/social_media
      - ./addons/oca/rest-framework:/mnt/oca-rest-framework
      - ./addons/oca/web-api:/mnt/oca-web-api
      - ./addons/oca/dms:/mnt/oca-dms
      - ./logs:/var/log/odoo
    tty: true
    stdin_open: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8069/web/health"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 120s

  mcp:
    build:
      context: ./libs/mcp-odoo
      dockerfile: Dockerfile
    depends_on:
      odoo:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      - ODOO_URL=http://odoo:8069
      - ODOO_DB=${ODOO_DB}
      - ODOO_USERNAME=${ODOO_USERNAME}
      - ODOO_PASSWORD=${ODOO_PASSWORD}
      - ODOO_TIMEOUT=30
      - ODOO_VERIFY_SSL=0
      - DEBUG=1
      - PYTHONUNBUFFERED=1
      - PG_URI=${PG_URI}
      - MCP_TRANSPORT=streamable-http
    volumes:
      - mcp-logs:/app/logs
    tty: true
    stdin_open: true
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

volumes:
  odoo-web-data:
  odoo-db-data:
  mcp-logs:
