services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: odoo
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  odoo:
    build: .
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=odoo
      - DB_PASSWORD=odoo
      - DB_NAME=odoo
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons/social_media:/mnt/social_media
      - ./addons/oca/rest-framework:/mnt/oca-rest-framework
      - ./addons/oca/web-api:/mnt/oca-web-api
      - ./addons/autodoo:/mnt/autodoo

volumes:
  odoo-web-data:
  odoo-db-data:
