services:
  odoo:
    build: .
    ports:
      - "8069:8069"
    environment:
      - DB_HOST=aws-0-eu-central-1.pooler.supabase.com
      - DB_PORT=5432
      - DB_USER=postgres.japcfankaqxrwyjzydsy
      - DB_PASSWORD=ciyrF86sP9gH&-J
      - DB_NAME=postgres
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    restart: unless-stopped

volumes:
  odoo-web-data:
