services:
  db:
    build:
      context: .
      dockerfile: db.Dockerfile
    environment:
      POSTGRES_DB: odoo
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    # Health check for PostgreSQL
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo -d odoo"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  odoo:
    build:
      context: .
      args:
        OPENAI_API_KEY: ${OPENAI_API_KEY}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8069:8069"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=odoo
      - DB_PASSWORD=odoo
      - DB_NAME=odoo
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PGPASSWORD=odoo
      - PYTHONUNBUFFERED=1
      - TERM=xterm-color
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons/setup_odoo:/mnt/setup_odoo
      - ./addons/social_media:/mnt/social_media
      - ./addons/oca/rest-framework:/mnt/oca-rest-framework
      - ./addons/oca/web-api:/mnt/oca-web-api
      - ./addons/oca/dms:/mnt/oca-dms
    tty: true
    stdin_open: true
    # Health check for Odoo web interface
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8069/web"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    command: >
      sh -c "echo 'Odoo configuration:';
      cat /etc/odoo/odoo.conf;
      python3 -u $$(which odoo) -c /etc/odoo/odoo.conf --workers=0 -i base,setup_odoo"

  mcp:
    build:
      context: ./libs/mcp-odoo
      dockerfile: Dockerfile
    depends_on:
      odoo:
        condition: service_healthy
      db:  # Add dependency on the database
        condition: service_healthy
    ports:
      - "42077:42077"
    environment:
      - ODOO_URL=http://odoo:8069
      - ODOO_DB=odoo
      - ODOO_USERNAME=admin
      - ODOO_PASSWORD=admin
      - ODOO_TIMEOUT=30
      - ODOO_VERIFY_SSL=0
      - DEBUG=1
      - PYTHONUNBUFFERED=1
      - PG_URI=postgresql://odoo:odoo@db:5432/odoo  # Add PostgreSQL URI
    volumes:
      - mcp-logs:/app/logs
    tty: true
    stdin_open: true
    command: python -u run_server.py
    restart: unless-stopped

volumes:
  odoo-web-data:
  odoo-db-data:
  mcp-logs:
