services:
  odoo:
    build:
      context: .
      args:
        OPENAI_API_KEY: ${OPENAI_API_KEY}
        HOST_UID: ${UID:-1000}
        HOST_GID: ${GID:-1000}
        DB_HOST: ${DB_HOST:-db}
        DB_PORT: ${DB_PORT:-5432}
        DB_USER: ${DB_USER:-odoo}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_NAME: ${DB_NAME:-odoo}
        PGPASSWORD: ${PGPASSWORD}
        ODOO_DB: ${ODOO_DB:-odoo}
        ODOO_USERNAME: ${ODOO_USERNAME:-admin}
        ODOO_PASSWORD: ${ODOO_PASSWORD}
        PG_URI: ${PG_URI}
    ports:
      - "8069:8069"
    environment:
      - DB_HOST=${DB_HOST:-db}
      - DB_PORT=${DB_PORT:-5432}
      - DB_USER=${DB_USER:-odoo}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME:-odoo}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PGPASSWORD=${PGPASSWORD}
      - ODOO_DB=${ODOO_DB:-odoo}
      - ODOO_USERNAME=${ODOO_USERNAME:-admin}
      - ODOO_PASSWORD=${ODOO_PASSWORD}
      - PG_URI=${PG_URI}
      - PYTHONUNBUFFERED=1
      - TERM=xterm-color
      - ODOO_LOGFILE=/var/log/odoo/odoo.log
      - ODOO_WORKERS=${ODOO_WORKERS:-0}
      - ODOO_LOG_LEVEL=${ODOO_LOG_LEVEL:-info}
      - ODOO_MAX_CRON_THREADS=${ODOO_MAX_CRON_THREADS:-2}
      - ODOO_PROXY_MODE=${ODOO_PROXY_MODE:-False}
      - DB_MAXCONN=${DB_MAXCONN:-64}
      - DB_TEMPLATE=${DB_TEMPLATE:-template0}
      # Module setup control
      - SKIP_MODULE_SETUP=${SKIP_MODULE_SETUP:-false}
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons/setup_odoo:/mnt/setup_odoo
      - ./addons/social_api:/mnt/social_api
      - ./addons/oca/rest-framework:/mnt/oca-rest-framework
      - ./addons/oca/web-api:/mnt/oca-web-api
      - ./addons/oca/dms:/mnt/oca-dms
      - ./logs:/var/log/odoo  # Mount logs directory for persistence
      # Mount the setup script
      - ./setup_odoo_modules.sh:/mnt/extra-addons/setup_odoo_modules.sh:ro
    tty: true
    stdin_open: true
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        mode: "non-blocking"
        tag: "odoo"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8069/web/health"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 120s

  # Utility service for running module setup only
  odoo-setup:
    build:
      context: .
      args:
        OPENAI_API_KEY: ${OPENAI_API_KEY}
        HOST_UID: ${UID:-1000}
        HOST_GID: ${GID:-1000}
        DB_HOST: ${DB_HOST:-db}
        DB_PORT: ${DB_PORT:-5432}
        DB_USER: ${DB_USER:-odoo}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_NAME: ${DB_NAME:-odoo}
        PGPASSWORD: ${PGPASSWORD}
        ODOO_DB: ${ODOO_DB:-odoo}
        ODOO_USERNAME: ${ODOO_USERNAME:-admin}
        ODOO_PASSWORD: ${ODOO_PASSWORD}
        PG_URI: ${PG_URI}
    environment:
      - DB_HOST=${DB_HOST:-db}
      - DB_PORT=${DB_PORT:-5432}
      - DB_USER=${DB_USER:-odoo}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME:-odoo}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PGPASSWORD=${PGPASSWORD}
      - ODOO_DB=${ODOO_DB:-odoo}
      - ODOO_USERNAME=${ODOO_USERNAME:-admin}
      - ODOO_PASSWORD=${ODOO_PASSWORD}
      - PG_URI=${PG_URI}
      - PYTHONUNBUFFERED=1
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons/setup_odoo:/mnt/setup_odoo
      - ./addons/social_api:/mnt/social_api
      - ./addons/oca/rest-framework:/mnt/oca-rest-framework
      - ./addons/oca/web-api:/mnt/oca-web-api
      - ./addons/oca/dms:/mnt/oca-dms
      - ./logs:/var/log/odoo
      - ./setup_odoo_modules.sh:/mnt/extra-addons/setup_odoo_modules.sh:ro
    profiles: ["tools"]  # Only run when specifically requested
    command: ["setup-modules-only"]

  mcp:
    build:
      context: ./libs/mcp-odoo
      dockerfile: Dockerfile
    depends_on:
      odoo:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      # Odoo connection settings
      - ODOO_URL=http://odoo:8069
      - ODOO_DB=${ODOO_DB:-odoo}
      - ODOO_USERNAME=${ODOO_USERNAME:-admin}
      - ODOO_PASSWORD=${ODOO_PASSWORD}
      - ODOO_TIMEOUT=30
      - ODOO_VERIFY_SSL=0
      
      # Database settings (THESE WERE MISSING)
      - DB_HOST=${DB_HOST:-db}
      - DB_PORT=${DB_PORT:-5432}
      - DB_USER=${DB_USER:-odoo}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME:-odoo}
      - PGPASSWORD=${PGPASSWORD}
      
      # API Keys
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      
      # Constructed URI
      - PG_URI=${PG_URI}
      
      # MCP settings
      - DEBUG=1
      - PYTHONUNBUFFERED=1
      - MCP_TRANSPORT=streamable-http
    volumes:
      - mcp-logs:/app/logs
    tty: true
    stdin_open: true
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

volumes:
  odoo-web-data:
  odoo-db-data:
  mcp-logs:
