services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: odoo
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  odoo:
    build: .
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      DB_HOST: aws-0-eu-central-1.pooler.supabase.com
      DB_PORT: 5432
      DB_USER: postgres.japcfankaqxrwyjzydsy
      DB_PASSWORD: "ciyrF86sP9gH&-J"
      DB_NAME: postgres
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons/ordo:/mnt/extra-addons
      - ./addons/oca/rest-framework:/mnt/oca-rest-framework
      - ./addons/oca/web-api:/mnt/oca-web-api
      - ./addons/autodoo:/mnt/autodoo
    restart: unless-stopped

volumes:
  odoo-web-data:
  odoo-db-data:
