name: Provision Infrastructure

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Terraform action'
        required: true
        default: apply
        type: choice
        options:
          - apply

env:
  ANSIBLE_FORCE_COLOR: 1
  ANSIBLE_HOST_KEY_CHECKING: false

jobs:
  terraform-provision:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.GIT_TOKEN }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Generate .auto.tfvars file
        working-directory: ./terraform
        run: |
          cat <<EOF > vars.auto.tfvars
          do_token = "${{ secrets.DO_TOKEN }}"
          ssh_public_key = <<EOTPUB
          ${{ secrets.SSH_PUBLIC_KEY }}
          EOTPUB
          ssh_private_key = <<EOT
          ${{ secrets.SSH_PRIVATE_KEY }}
          EOT
          namecom_username = "${{ vars.NAMECOM_USERNAME }}"
          namecom_token = "${{ secrets.NAMECOM_TOKEN }}"
          domain_name = "kajande.com"
          EOF

      - name: Terraform Init (Cloud)
        working-directory: ./terraform
        env:
          TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}
        run: terraform init

      - name: Terraform Apply
        working-directory: ./terraform
        env:
          TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}
        run: terraform apply -auto-approve
